(() => {
  'use strict';
  const assets={{tableAssets}};
  const reference={{tableData}};
  const host=document.getElementById('table-view');
  const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const img=name=>assets[name]||assets['user-1.jpg'];
  const assetName=url=>url.split('/').pop().split('?')[0];
  const icon=name=>`<i data-lucide="${name}"></i>`;
  const button=(name,label,attrs='')=>`<button class="table-action" type="button" aria-label="${escape(label)}" title="${escape(label)}" ${attrs}>${icon(name)}</button>`;
  const names={orders:'Order Table','tables/basic':'Basic Table','tables/collapsible':'Collapsible Table','tables/enhanced':'Enhanced Table','tables/fixed-header':'Fixed Header Table','tables/pagination':'Pagination Table','tables/search':'Search Table'};
  const statusColor=value=>({Active:'green',active:'green',Pending:'gold',pending:'green',Completed:'',Cancelled:'red',Cancel:'red',cancel:'red',cancelled:'red',Shipped:'sky',Processing:'',paid:'',refunded:'sky',offline:'gray',InStock:'green','In Stock':'green','Out of Stock':'red'}[value]||'');
  const chip=(value,extra='')=>`<span class="status-chip ${statusColor(value)} ${extra}">${escape(value)}</span>`;
  const inlineStatus=value=>`<span class="status-inline ${statusColor(value)}">${escape(value)}</span>`;
  const person=(name,subtitle,photo,kind='')=>`<div class="person ${kind}"><img class="avatar" src="${img(photo)}" alt="" width="40" height="40"><div><strong>${escape(name)}</strong>${subtitle?`<p>${escape(subtitle)}</p>`:''}</div></div>`;
  const colors=['#fa896b','#49beff','#ffae1f','#5d87ff'];
  const letters=team=>`<div class="team-letters">${team.map((letter,i)=>`<span class="team-letter" style="background:${colors[i%4]}">${escape(letter)}</span>`).join('')}</div>`;
  const avatarGroup=index=>`<div class="table-avatars">${[index%6+1,(index+1)%6+1,...(index%2?[3]:[])].map(n=>`<img class="avatar" src="${img('user-'+n+'.jpg')}" alt="Team member ${n}">`).join('')}</div>`;
  const money2=value=>Number(value).toLocaleString('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2});
  const orders=[
    {id:'ORD-001',customer:'John Doe',status:'Pending',date:'06-10-2025',time:'10:31AM',amount:120,address:'123 Main St, New York, NY',photo:'user-4.jpg'},
    {id:'ORD-002',customer:'Jane Smith',status:'Completed',date:'06-09-2025',time:'11:31AM',amount:150,address:'456 Elm St, Los Angeles, CA',photo:'user-6.jpg'},
    {id:'ORD-003',customer:'Bob Johnson',status:'Shipped',date:'06-08-2025',time:'12:01AM',amount:210,address:'789 Pine St, Chicago, IL',photo:'user-7.jpg'},
    {id:'ORD-004',customer:'Georgeanna Ramero',status:'Cancelled',date:'06-08-2025',time:'01:06AM',amount:310,address:'19214 110th Rd, Saint Albans, NY, 1141',photo:'user-2.jpg'},
    {id:'ORD-005',customer:'Dalton Paden',status:'Processing',date:'2025-06-08',time:'02:34AM',amount:600,address:'19103 Stefani Ave, Cerritos, CA, 90703',photo:'user-6.jpg'},
    {id:'ORD-006',customer:'Cami Macha',status:'Pending',date:'06-08-2025',time:'02:34AM',amount:500,address:'930 Fruit Ave, Farrell, PA, 16121',photo:'user-3.jpg'}
  ];
  const people=reference.enhanced.map((row,i)=>({id:'person-'+i,name:row.cells[1].split('\n')[0],email:row.cells[1].split('\n')[1],project:row.cells[2],team:row.cells[3].split('\n'),status:row.cells[4],weeks:Number(row.cells[5]),budget:row.cells[6],photo:assetName(row.images[0]),role:['Web Designer','Project Manager','Project Manager','Frontend Engineer','Content Writer'][i%5]}));
  const products=reference.search.filter(row=>row.cells.length>2).map((row,i)=>({id:'product-'+i,name:row.cells[1].split('\n')[0],category:row.cells[1].split('\n')[1],date:row.cells[2],status:row.cells[3],price:Number(row.cells[4].replace('$','')),photo:assetName(row.images[0])}));
  const catalogue=[
    {id:'catalogue-0',name:'Good butterscotch ice-cream',customer:'Sunil Joshi',status:'In Stock',price:250,items:2,photo:'s1.jpg',description:'Ice-Cream, Milk, Powder',review:'Good',sold:65,earnings:546000},
    {id:'catalogue-1',name:'Supreme fresh tomato available',customer:'John Deo',status:'Out of Stock',price:450,items:1,photo:'s2.jpg',description:'Market, Mall',review:'Excellent',sold:98,earnings:780000},
    {id:'catalogue-2',name:'Red color candy from Gucci',customer:'Andrew McDownland',status:'Out of Stock',price:150,items:2,photo:'s3.jpg',description:'Chocolate, Yummy',review:'Average',sold:46,earnings:457000},
    {id:'catalogue-3',name:'Stylish night lamp for night',customer:'Christopher Jamil',status:'In Stock',price:550,items:6,photo:'s4.jpg',description:'Elecric, Wire, Current',review:'Poor',sold:23,earnings:125000}
  ];
  const paginated=reference.pagination.filter(row=>row.cells.length>2).map((row,i)=>({id:'pagination-'+i,order:row.cells[0],customer:row.cells[1],items:row.cells[2],total:row.cells[3],date:row.cells[4],status:row.cells[5],photo:assetName(row.images[0])}));
  const customers=['Olivia Rhye','Barbara Steele','Leonard Gordon','Evelyn Pope','Tommy Garza','Isabel Vasquez'].map((name,i)=>({id:'customer-'+i,name,handle:['rhye','steele','gordon','pope','garza','vasquez'][i],email:i%2?'steele@ui.com':'olivia@ui.com',project:['Xtreme admin','Adminpro admin','Monster admin','Materialpro admin','Elegant admin','Modernize admin'][i],status:['active','cancel','active','pending','cancel','pending'][i],teams:[['Design','Product'],['Product','Operations'],['Finance','Customer Success'],['Operations','Design'],['Product'],['Customer Success']][i],photo:'user-'+(i+1)+'.jpg'}));
  const stores={orders,'tables/enhanced':people,'tables/search':products,'tables/fixed-header':catalogue.map(row=>({...row})),'tables/pagination':paginated};
  const states={};let route='dashboard',menuRecord=null,menuOpener=null,undoAction=null,editId=null;
  const state=()=>states[route]||(states[route]={page:0,size:route==='orders'?10:5,query:'',filter:'All',filterOpen:false,searchOpen:false,columnsOpen:false,hiddenColumns:new Set(),selected:new Set(),expanded:new Set(),sort:null,direction:1,dense:false});
  function renderIcons(){lucide.createIcons({attrs:{class:'icon','aria-hidden':'true'}})}
  function banner(){return `<div class="page-banner"><div><h1 tabindex="-1">${names[route]}</h1><nav class="breadcrumb" aria-label="Breadcrumb"><a href="#/dashboard">${route==='orders'?'Dashboard':'Home'}</a><span aria-hidden="true"></span><span aria-current="page">${names[route]}</span></nav></div><img src="${img('ChatBc.png')}" alt="" width="165" height="165"></div>`}
  const panel=(title,content)=>`<section class="view-panel"><div class="view-panel-title"><h2>${title}</h2></div><div class="view-panel-body">${content}</div></section>`;
  const frame=(content,extra='')=>`<div class="data-frame ${extra}">${content}</div>`;
  const table=(headers,rows,extra='')=>`<div class="data-scroll"><table class="data-table ${extra}"><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;
  const cells=values=>values.map(value=>`<td>${value}</td>`).join('');
  const more=(id,group)=>button('ellipsis-vertical','Actions for '+id,`data-row-menu="${id}" data-group="${group}" aria-haspopup="menu" aria-expanded="false"`);
  const empty=columns=>`<tr><td class="empty-row" colspan="${columns}">No results found.</td></tr>`;
  function basic(){
    const first=people.slice(0,5).map(row=>`<tr>${cells([person(row.name,row.role,row.photo),escape(row.project),letters(row.team),chip(row.status),`<strong>${row.budget}</strong>`])}</tr>`).join('');
    const second=customers.map((row,i)=>`<tr>${cells([person(row.name,'',row.photo),escape(row.project),avatarGroup(i),chip(row.status,'round'),more(row.id,'customers')])}</tr>`).join('');
    const third=customers.map((row,i)=>`<tr>${cells([person(row.name,'@'+row.handle,row.photo),chip(i===1||i===3?'offline':'active','round'),escape(row.email),`<div class="team-tags">${row.teams.map(t=>`<span style="background:${{Design:'#5d87ff',Product:'#49beff',Operations:'#fa896b',Finance:'#5d87ff','Customer Success':'#13caaa'}[t]}">${t}</span>`).join('')}</div>`,more(row.id,'customers')])}</tr>`).join('');
    const fourth=customers.map((row,i)=>`<tr>${cells([`INV-${3066+i}`,chip(['paid','cancelled','paid','refunded','cancelled','refunded'][i],'round'),person(row.name,row.email,row.photo),`<div class="invoice-progress"><div class="review-progress"><span style="width:${[60,30,45,37,87,32][i]}%"></span></div><span>${[60,30,45,37,87,32][i]}%</span></div>`,more(row.id,'customers')])}</tr>`).join('');
    const authors=[['Top Authors','Successful Fellas',['Angular','PHP'],4300],['Popular Authors','Most Successful',['Bootstrap'],1200],['New Users','Awesome Users',['Reactjs','Angular'],2000],['Active Customers','Best Customers',['Bootstrap'],1500],['Bestseller Theme','Amazing Templates',['Angular','Reactjs'],9500]].map((row,i)=>`<tr>${cells([person(row[0],row[1],'blog-img'+(i+1)+'.jpg'),`<div class="team-tags">${row[2].map(t=>chip(t)).join('')}</div>`,row[3]+' Users',button('ellipsis','View author details',`data-author="${i}"`)])}</tr>`).join('');
    return panel('Basic Table',frame(table(['Users','Project Name','Team','Status','Budget'],first))+frame(table(['User','Project Name','Users','Status','<span class="small"> </span>'],second))+frame(table(['Customer','Status','Email Address','Teams',''],third))+frame(table(['Invoice','Status','Customer','Progress',''],fourth))+frame(table(['Authors','Courses','Users',''],authors)));
  }
  function collapsible(){
    const s=state();
    const rows=catalogue.map(row=>`<tr>${cells([button(s.expanded.has(row.id)?'chevron-up':'chevron-down','Toggle history for '+row.name,`data-expand="${row.id}" aria-expanded="${s.expanded.has(row.id)}" aria-controls="history-${row.id}"`),person(row.name,'',row.photo,'product-person'),`<strong>${row.customer}</strong>`,chip(row.status,'solid'),'$'+row.price,row.items])}</tr><tr class="detail-row" id="history-${row.id}" ${s.expanded.has(row.id)?'':'hidden'}><td colspan="6"><div class="expanded-detail"><h3>History</h3><table><thead><tr><th scope="col">Date</th><th scope="col">Customer</th><th scope="col">Amount</th><th scope="col">Total price ($)</th></tr></thead><tbody><tr class="history-row"><td>2021-02-05</td><td>15202410</td><td>3</td><td>${row.price*3}</td></tr><tr class="history-row"><td>2021-02-02</td><td>Anonymous</td><td>1</td><td>600</td></tr></tbody></table></div></td></tr>`).join('');
    return panel('Collapsible',frame(table(['','Product','Customer','Inventory','Price','Items'],rows)));
  }
  function filtered(){const s=state();let list=stores[route].filter(row=>(s.filter==='All'||row.status===s.filter)&&Object.values(row).join(' ').toLowerCase().includes(s.query.toLowerCase()));if(s.sort)list=list.toSorted((a,b)=>{let av=a[s.sort],bv=b[s.sort];if(s.sort==='budget'||s.sort==='total'){av=parseFloat(String(av).replace(/[^\d.]/g,''));bv=parseFloat(String(bv).replace(/[^\d.]/g,''))}if(s.sort==='date'){av=Date.parse(av);bv=Date.parse(bv)}return s.direction*(typeof av==='number'?av-bv:String(av).localeCompare(String(bv),undefined,{numeric:true}))});return list}
  function pageData(){const s=state(),all=filtered(),size=s.size===-1?Math.max(all.length,1):s.size;s.page=Math.min(s.page,Math.max(0,Math.ceil(all.length/size)-1));return {all,rows:all.slice(s.page*size,(s.page+1)*size),size}}
  function footer(){const s=state(),{all,size}=pageData(),start=all.length?s.page*size+1:0,end=Math.min((s.page+1)*size,all.length);return `<div class="table-footer"><label>Rows per page:<select aria-label="Rows per page" data-size>${[5,10,25,-1].map(n=>`<option value="${n}" ${n===s.size?'selected':''}>${n===-1?'All':n}</option>`).join('')}</select></label><span aria-live="polite">${start}&ndash;${end} of ${all.length}</span><div class="page-controls">${button('chevron-left','Previous page',`data-page="-1" ${s.page===0?'disabled':''}`)}${button('chevron-right','Next page',`data-page="1" ${end>=all.length?'disabled':''}`)}</div></div>`}
  function checkbox(id,label){return `<input type="checkbox" aria-label="${escape(label)}" data-select="${id}" ${state().selected.has(id)?'checked':''}>`}
  const checkAll=()=>'<input type="checkbox" data-select-all aria-label="Select all rows on this page">';
  function header(label,key){const s=state();return `<button class="sort-button" data-sort="${key}">${label}${icon(s.sort===key?(s.direction===1?'arrow-up':'arrow-down'):'arrow-down-up')}</button>`}
  function density(){return `<label class="density"><input type="checkbox" role="switch" data-density ${state().dense?'checked':''}>Dense padding</label>`}
  function filterBar(){const s=state();if(!s.filterOpen)return '';return `<div class="filter-bar"><label>Status<select class="table-field" data-filter aria-label="Filter by status">${['All',...new Set(stores[route].map(row=>row.status))].map(value=>`<option ${s.filter===value?'selected':''}>${value}</option>`).join('')}</select></label>${s.filter!=='All'?'<button class="secondary-button" data-clear-filter>Clear</button>':''}</div>`}
  function searchField(placeholder){return `<label class="table-search">${icon('search')}<input type="search" aria-label="${placeholder}" placeholder="${placeholder}" value="${escape(state().query)}" data-query></label>`}
  function toolbar(title,search=false){const s=state();return `<div class="table-toolbar ${s.selected.size?'selected-toolbar':''}">${s.selected.size?`<h3>${s.selected.size} selected</h3>`:search?searchField('Search Product'):`<h3>${title}</h3>`}<div class="toolbar-actions">${s.selected.size?button('trash-2','Delete selected rows','data-delete-selected'):''}${button('filter','Filter by status',`data-toggle-filter aria-expanded="${s.filterOpen}"`)}</div></div>${filterBar()}`}
  function enhanced(){const {rows}=pageData(),s=state();return panel('Enhanced Table',frame(toolbar('Filter')+table([checkAll(),header('Team Lead','name'),header('Project Name','project'),'Team',header('Status','status'),header('Weeks','weeks'),header('Budget','budget')],rows.map(row=>`<tr class="${s.selected.has(row.id)?'selected':''}">${cells([checkbox(row.id,'Select '+row.name),person(row.name,row.email,row.photo),escape(row.project),letters(row.team),inlineStatus(row.status),row.weeks,`<strong>${row.budget}</strong>`])}</tr>`).join('')||empty(7),s.dense?'dense':'')+footer()+density()))}
  function fixed(){const rows=stores[route].map((row,i)=>`<tr>${cells([person(i===0?'Is it good butterscotch ice-cream?':row.name,row.description,row.photo,'product-person'),`${row.review}<div class="review-progress"><span style="width:${row.sold}%;background:${['#5d87ff','#13deb9','#ffae1f','#fa896b'][i%4]}"></span></div>${row.sold}% sold`,`Earnings<p class="amount">${money(row.earnings)}</p>`,button('trash-2','Delete '+row.name,`data-delete="${row.id}"`)])}</tr>`).join('');return panel('Fixed Header Table',frame(`<div class="data-scroll fixed-table-scroll" tabindex="0" aria-label="Scrollable products table"><table class="data-table"><thead><tr>${['Products','Review','Earnings','Action'].map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows||empty(4)}</tbody></table></div>`))}
  function pagination(){const {rows}=pageData();return panel('Pagination Table',frame(table(['Order No.','Customer','Items','Total','Date','Status'],rows.map(row=>`<tr>${cells([`<strong>${row.order}</strong>`,person(row.customer,'',row.photo),row.items,row.total,escape(row.date),chip(row.status,'solid')])}</tr>`).join('')||empty(6))+footer()))}
  function searchTable(){const {rows}=pageData(),s=state();return panel('Search',toolbar('',true)+frame(table([checkAll(),header('Products','name'),header('Date','date'),header('Status','status'),header('Price','price'),'Action'],rows.map(row=>`<tr class="${s.selected.has(row.id)?'selected':''}">${cells([checkbox(row.id,'Select '+row.name),person(row.name,row.category,row.photo,'search-person'),`<span class="nowrap">${row.date}</span>`,inlineStatus(row.status),`<strong>$${row.price}</strong>`,more(row.id,'products')])}</tr>`).join('')||empty(6),s.dense?'dense':'')+footer())+density())}
  const orderColumns=[['id','ID'],['customer','CUSTOMER'],['status','STATUS'],['date','DATE'],['amount','AMOUNT'],['address','ADDRESS']];
  function orderDetails(row){return `<dl><div><dt>Order</dt><dd>${row.id}</dd></div><div><dt>Customer</dt><dd>${escape(row.customer)}</dd></div><div><dt>Status</dt><dd>${chip(row.status)}</dd></div><div><dt>Date</dt><dd>${escape(row.date)} ${row.time}</dd></div><div><dt>Amount</dt><dd>${money2(row.amount)}</dd></div><div><dt>Address</dt><dd>${escape(row.address)}</dd></div></dl>`}
  function ordersView(){
    const s=state(),{rows}=pageData(),columns=orderColumns.filter(([key])=>!s.hiddenColumns.has(key));
    const stats=[['$95.3k','Income','circle-dollar-sign',''],['485','Pending','clock','green'],['1.4k','Completed','badge-check','gold'],['996','Shipping','truck','blue'],['2.1k','Processing','refresh-cw','blue'],['1.1k','Cancelled','circle-x','red']];
    const top=`<h2>Orders History</h2><div class="order-stats">${stats.map(([amount,label,symbol,color])=>`<div class="order-stat ${color}"><strong>${amount}</strong><p>${label}</p>${icon(symbol)}</div>`).join('')}</div><div class="table-toolbar ${s.selected.size?'selected-toolbar':''}"><h3>${s.selected.size?s.selected.size+' selected':'Orders Table'}</h3><div class="toolbar-actions">${s.selected.size?button('trash-2','Delete selected orders','data-delete-selected'):''}${button('search','Search orders',`data-toggle-search aria-expanded="${s.searchOpen}"`)}${button('filter','Filter orders',`data-toggle-filter aria-expanded="${s.filterOpen}"`)}${button('settings','Choose columns',`data-toggle-columns aria-expanded="${s.columnsOpen}"`)}${button('download','Download orders CSV','data-orders-export')}</div></div>${s.searchOpen?`<div class="filter-bar">${searchField('Search orders')}</div>`:''}${filterBar()}${s.columnsOpen?`<div class="filter-bar"><div class="column-choices">${orderColumns.map(([key,label])=>`<label><input type="checkbox" data-column="${key}" ${s.hiddenColumns.has(key)?'':'checked'}>${label}</label>`).join('')}</div></div>`:''}`;
    const rowsHtml=rows.map(row=>{const values={id:`<span>${row.id}</span>`,customer:person(row.customer,'',row.photo),status:`<span class="status-chip round ${row.status==='Pending'?'green':row.status==='Completed'?'gold':statusColor(row.status)}">${row.status}</span>`,date:`${row.date}<br><small>${row.time}</small>`,amount:money2(row.amount),address:escape(row.address)};return `<tr class="${s.selected.has(row.id)?'selected':''}"><td class="check-cell">${checkbox(row.id,'Select '+row.id)}</td>${columns.map(([key])=>`<td class="${key==='id'?'order-id':key==='address'?'address-cell':key==='date'?'date-cell':''}">${values[key]}</td>`).join('')}<td><div class="table-actions">${button(s.expanded.has(row.id)?'chevron-up':'chevron-down','Details for '+row.id,`data-expand="${row.id}" aria-controls="detail-${row.id}" aria-expanded="${s.expanded.has(row.id)}"`)}${more(row.id,'orders')}</div></td></tr><tr class="detail-row" id="detail-${row.id}" ${s.expanded.has(row.id)?'':'hidden'}><td colspan="${columns.length+2}"><div class="expanded-detail">${orderDetails(row)}</div></td></tr>`}).join('');
    const headers=`<th scope="col" class="check-cell">${checkAll()}</th>${columns.map(([key,label])=>`<th scope="col" aria-sort="${s.sort===key?(s.direction===1?'ascending':'descending'):'none'}">${header(label,key)}</th>`).join('')}<th scope="col">ACTIONS</th>`;
    return `<section class="view-panel orders-panel">${top}${frame(`<div class="data-scroll"><table class="data-table orders-table"><thead><tr>${headers}</tr></thead><tbody>${rowsHtml||empty(columns.length+2)}</tbody></table></div>`)}${footer()}</section>`;
  }
  function render(){
    const builders={orders:ordersView,'tables/basic':basic,'tables/collapsible':collapsible,'tables/enhanced':enhanced,'tables/fixed-header':fixed,'tables/pagination':pagination,'tables/search':searchTable};
    if(!builders[route])return;
    host.innerHTML=banner()+builders[route]();renderIcons();
    const all=host.querySelector('[data-select-all]');if(all){const rows=pageData().rows,selected=rows.filter(row=>state().selected.has(row.id)).length;all.checked=rows.length>0&&selected===rows.length;all.indeterminate=selected>0&&selected<rows.length}
    host.querySelectorAll('[data-sort]').forEach(b=>b.closest('th').setAttribute('aria-sort',state().sort===b.dataset.sort?(state().direction===1?'ascending':'descending'):'none'));
  }
  function navigate(initial=false){
    const hash=location.hash.replace(/^#\//,'');if(location.hash&&!location.hash.startsWith('#/'))return;
    route=names[hash]?hash:'dashboard';
    document.getElementById('dashboard-view').hidden=route!=='dashboard';host.hidden=route==='dashboard';
    document.querySelectorAll('#navigation [data-local]').forEach(a=>{const active=a.dataset.local===route;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});
    document.title='Modernize | '+(names[route]||'Dashboard');closeOverlays();closePopovers();closeMenu();render();
    if(!initial){window.scrollTo(0,0);host.querySelector('h1')?.focus({preventScroll:true})}
  }
  const detailDialog=document.createElement('dialog');detailDialog.id='record-dialog';detailDialog.setAttribute('aria-labelledby','record-title');document.body.append(detailDialog);
  const menu=document.createElement('div');menu.className='row-menu';menu.hidden=true;menu.setAttribute('role','menu');document.body.append(menu);
  const notice=document.createElement('div');notice.className='undo-notice';notice.hidden=true;notice.setAttribute('role','status');document.body.append(notice);
  function showNotice(text,undo){undoAction=undo;notice.innerHTML=`<p>${escape(text)}</p>${undo?'<button data-undo>Undo</button>':''}<button aria-label="Dismiss notification" data-dismiss>${icon('x')}</button>`;notice.hidden=false;renderIcons()}
  notice.addEventListener('click',event=>{if(event.target.closest('[data-undo]')){undoAction?.();render()}if(event.target.closest('button')){notice.hidden=true;undoAction=null}});
  function closeMenu(){menu.hidden=true;if(menuOpener)menuOpener.setAttribute('aria-expanded','false')}
  function lookup(group,id){return (group==='orders'?orders:group==='products'?products:group==='customers'?customers:people).find(row=>row.id===id)}
  function showRecord(row,group){
    const entries=group==='orders'?[['Order',row.id],['Customer',row.customer],['Status',row.status],['Date',row.date+' '+row.time],['Amount',money2(row.amount)],['Address',row.address]]:group==='customers'?[['Customer',row.name],['Email Address',row.email],['Project',row.project],['Status',row.status],['Teams',row.teams.join(', ')]]:[['Product',row.name],['Category',row.category],['Date',row.date],['Status',row.status],['Price','$'+row.price]];
    detailDialog.innerHTML=`<div class="dialog-heading"><h2 id="record-title">${group==='orders'?escape(row.id):escape(row.name)}</h2><button class="icon-button" data-record-close aria-label="Close details">${icon('x')}</button></div><dl class="record-details">${entries.map(([key,value])=>`<div><dt>${key}</dt><dd>${escape(value)}</dd></div>`).join('')}</dl>${group==='orders'?`<div class="dialog-buttons"><button class="primary-button" data-record-edit="${row.id}">${icon('pencil')}Edit order</button></div>`:''}`;
    renderIcons();detailDialog.showModal();
  }
  function editOrder(row){
    editId=row.id;
    detailDialog.innerHTML=`<div class="dialog-heading"><h2 id="record-title">Edit ${row.id}</h2><button class="icon-button" data-record-close aria-label="Close edit order">${icon('x')}</button></div><form id="order-edit-form"><div class="edit-grid"><label>Customer<input class="table-field" name="customer" value="${escape(row.customer)}" required maxlength="100"></label><label>Status<select class="table-field" name="status">${['Pending','Completed','Shipped','Cancelled','Processing'].map(s=>`<option ${s===row.status?'selected':''}>${s}</option>`).join('')}</select></label><label>Amount<input class="table-field" name="amount" type="number" min="0" step="0.01" required value="${row.amount}"></label><label class="full">Address<input class="table-field" name="address" value="${escape(row.address)}" required maxlength="200"></label></div><div class="dialog-buttons"><button type="button" class="secondary-button" data-record-close>Cancel</button><button type="submit" class="primary-button">Save changes</button></div></form>`;
    renderIcons();if(!detailDialog.open)detailDialog.showModal();detailDialog.querySelector('input').focus();
  }
  detailDialog.addEventListener('click',event=>{if(event.target.closest('[data-record-close]'))detailDialog.close();const edit=event.target.closest('[data-record-edit]');if(edit)editOrder(orders.find(row=>row.id===edit.dataset.recordEdit))});
  detailDialog.addEventListener('submit',event=>{event.preventDefault();const form=event.target;if(!form.reportValidity())return;const values=new FormData(form),row=orders.find(r=>r.id===editId),before={...row};if(!row)return;Object.assign(row,{customer:values.get('customer').trim(),status:values.get('status'),amount:Number(values.get('amount')),address:values.get('address').trim()});detailDialog.close();render();showNotice(row.id+' updated',()=>Object.assign(row,before))});
  detailDialog.addEventListener('click',event=>{const r=detailDialog.getBoundingClientRect();if(event.target===detailDialog&&(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom))detailDialog.close()});
  function deleteRows(ids){const currentRoute=route,store=stores[currentRoute],removed=store.map((row,index)=>({row,index})).filter(item=>ids.includes(item.row.id));for(let i=store.length-1;i>=0;i--)if(ids.includes(store[i].id))store.splice(i,1);state().selected.clear();render();showNotice(removed.length+' '+(removed.length===1?'row':'rows')+' deleted',()=>{removed.forEach(({row,index})=>store.splice(index,0,row));states[currentRoute].selected.clear()})}
  function exportOrders(){const rows=filtered(),data=[['ID','Customer','Status','Date','Time','Amount','Address'],...rows.map(row=>[row.id,row.customer,row.status,row.date,row.time,row.amount.toFixed(2),row.address])];const csv=data.map(row=>row.map(value=>'"'+String(value).replaceAll('"','""')+'"').join(',')).join('\r\n');download(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),'orders.csv')}
  function rerenderFocus(attribute){render();host.querySelector(attribute)?.focus({preventScroll:true})}
  host.addEventListener('click',event=>{
    const target=event.target.closest('button');if(!target)return;const s=state();
    if(target.hasAttribute('data-page')){s.page+=Number(target.dataset.page);rerenderFocus(`[data-page="${target.dataset.page}"]:not(:disabled)`)}
    else if(target.hasAttribute('data-sort')){const key=target.dataset.sort;s.direction=s.sort===key?-s.direction:1;s.sort=key;rerenderFocus(`[data-sort="${key}"]`)}
    else if(target.hasAttribute('data-expand')){const id=target.dataset.expand;if(s.expanded.has(id))s.expanded.delete(id);else s.expanded.add(id);rerenderFocus(`[data-expand="${id}"]`)}
    else if(target.hasAttribute('data-toggle-filter')){s.filterOpen=!s.filterOpen;rerenderFocus('[data-toggle-filter]')}
    else if(target.hasAttribute('data-toggle-search')){s.searchOpen=!s.searchOpen;if(!s.searchOpen){s.query='';s.page=0}rerenderFocus(s.searchOpen?'[data-query]':'[data-toggle-search]')}
    else if(target.hasAttribute('data-toggle-columns')){s.columnsOpen=!s.columnsOpen;rerenderFocus('[data-toggle-columns]')}
    else if(target.hasAttribute('data-clear-filter')){s.filter='All';s.page=0;render()}
    else if(target.hasAttribute('data-orders-export'))exportOrders();
    else if(target.hasAttribute('data-delete-selected'))deleteRows([...s.selected]);
    else if(target.hasAttribute('data-delete'))deleteRows([target.dataset.delete]);
    else if(target.hasAttribute('data-row-menu')){
      event.stopPropagation();
      menuRecord={row:lookup(target.dataset.group,target.dataset.rowMenu),group:target.dataset.group};menuOpener=target;const canDelete=route==='orders'||route==='tables/search';menu.innerHTML=`<button role="menuitem" data-menu-action="view">${icon('eye')}View details</button>${menuRecord.group==='orders'?`<button role="menuitem" data-menu-action="edit">${icon('pencil')}Edit order</button>`:''}${canDelete?`<button role="menuitem" class="danger" data-menu-action="delete">${icon('trash-2')}Delete</button>`:''}`;menu.hidden=false;const r=target.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(r.right-165,innerWidth-173))+'px';menu.style.top=Math.max(8,Math.min(r.bottom+4,innerHeight-menu.offsetHeight-8))+'px';target.setAttribute('aria-expanded','true');renderIcons();menu.querySelector('button').focus();
    }else if(target.hasAttribute('data-author')){const author=Number(target.dataset.author);detailDialog.innerHTML=`<div class="dialog-heading"><h2 id="record-title">${['Top Authors','Popular Authors','New Users','Active Customers','Bestseller Theme'][author]}</h2><button class="icon-button" data-record-close aria-label="Close details">${icon('x')}</button></div><p>${[4300,1200,2000,1500,9500][author].toLocaleString('en-US')} Users</p>`;renderIcons();detailDialog.showModal()}
  });
  host.addEventListener('change',event=>{const target=event.target,s=state();if(target.hasAttribute('data-size')){s.size=Number(target.value);s.page=0;rerenderFocus('[data-size]')}else if(target.hasAttribute('data-select')){if(target.checked)s.selected.add(target.dataset.select);else s.selected.delete(target.dataset.select);rerenderFocus(`[data-select="${target.dataset.select}"]`)}else if(target.hasAttribute('data-select-all')){pageData().rows.forEach(row=>target.checked?s.selected.add(row.id):s.selected.delete(row.id));rerenderFocus('[data-select-all]')}else if(target.hasAttribute('data-density')){s.dense=target.checked;rerenderFocus('[data-density]')}else if(target.hasAttribute('data-filter')){s.filter=target.value;s.page=0;rerenderFocus('[data-filter]')}else if(target.hasAttribute('data-column')){target.checked?s.hiddenColumns.delete(target.dataset.column):s.hiddenColumns.add(target.dataset.column);rerenderFocus(`[data-column="${target.dataset.column}"]`)}});
  host.addEventListener('input',event=>{if(event.target.hasAttribute('data-query')){const start=event.target.selectionStart,end=event.target.selectionEnd;state().query=event.target.value;state().page=0;render();const input=host.querySelector('[data-query]');input.focus({preventScroll:true});input.setSelectionRange(start,end)}});
  menu.addEventListener('click',event=>{const action=event.target.closest('[data-menu-action]')?.dataset.menuAction;if(!action)return;closeMenu();const {row,group}=menuRecord;if(action==='view')showRecord(row,group);if(action==='edit')editOrder(row);if(action==='delete')deleteRows([row.id])});
  document.addEventListener('click',event=>{if(!event.target.closest('[data-row-menu]')&&!menu.contains(event.target))closeMenu()});
  document.addEventListener('keydown',event=>{if(menu.hidden)return;const buttons=[...menu.querySelectorAll('button')],index=buttons.indexOf(document.activeElement);if(event.key==='Escape'){closeMenu();menuOpener?.focus()}if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();buttons[(index+(event.key==='ArrowDown'?1:buttons.length-1))%buttons.length].focus()}if(event.key==='Tab')closeMenu()});
  window.addEventListener('resize',closeMenu);window.addEventListener('wheel',closeMenu,{passive:true});window.addEventListener('hashchange',()=>navigate());
  navigate(true);
})();
